# Generated by Django 2.1.5 on 2021-06-07 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('user_name', models.CharField(max_length=30)),
                ('EMail', models.EmailField(max_length=254)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('date_registered', models.DateField(default=datetime.date(2021, 6, 7))),
                ('password', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
